version: '3'
services:
  redis-server:
    image: redis
    ports:
    - 6379:6379
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
  my-app:
    build: .
    ports:
    - 7868:7868
    restart: always
    environment:
      DB_URL: jdbc:mysql://my-sql:3306/fileservice?zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowPublicKeyRetrieval=true&failOverReadOnly=false&maxReconnects=2&useSSL=false
      DB_UNAME: root
      DB_PWD: root
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    depends_on:
      - my-sql
      - redis-server
  my-sql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
     