From maven As build
WORKDIR "/my-springboot-app"
COPY . .
RUN mvn clean package -DskipTests


FROM openjdk:8-jdk-alpine
COPY --from=build /my-springboot-app/target/File-Service-0.0.1-SNAPSHOT.jar File-Service.jar
EXPOSE 8989
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=docker","-jar","File-Service.jar"]